name: Build iOS
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-26

    env:
      Solution_Name_MB: "Media Blocks SDK/VisioForge.MediaBlocks.Demos.CS iOS.sln"
      Solution_Name_VC: "Video Capture SDK X/VisioForge.VideoCaptureX.Demos.CS iOS.sln"

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 26.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.2"

      - name: Setup .NET (ARM64)
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash -s -- --channel 9.0 --architecture arm64
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash -s -- --channel 10.0 --architecture arm64
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV

      - name: Install workloads
        run: dotnet workload install ios

      # Media Blocks
      - name: Build (Media Blocks)
        run: dotnet build "${{ env.Solution_Name_MB }}" --configuration Release /p:_RequireCodeSigning=false /p:CodesignKey="-"

      # Video Capture
      - name: Build (Video Capture)
        run: dotnet build "${{ env.Solution_Name_VC }}" --configuration Release /p:_RequireCodeSigning=false /p:CodesignKey="-"
