name: Build Uno Platform
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name_MB1: "Media Blocks SDK/VisioForge.MediaBlocks.Demos.CS Uno.sln"
      Solution_Name_MP1: "Media Player SDK X/VisioForge.MediaPlayer.X.Demos.CS.Uno.sln"
      Solution_Name_VC1: "Video Capture SDK X/VisioForge.VideoCaptureX.Demos.CS Uno.sln"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          10.0.x
          9.0.x
          8.0.x

    - name: Install workloads
      run: dotnet workload install android

    ## Media Blocks

    - name: Restore dependencies $env:Solution_Name_MB1
      run: 'dotnet restore "$env:Solution_Name_MB1"'

    - name: Build app for release $env:Solution_Name_MB1
      run: 'dotnet build "$env:Solution_Name_MB1" --configuration Release --no-restore'

    ## Media Player

    - name: Restore dependencies $env:Solution_Name_MP1
      run: 'dotnet restore "$env:Solution_Name_MP1"'

    - name: Build app for release $env:Solution_Name_MP1
      run: 'dotnet build "$env:Solution_Name_MP1" --configuration Release --no-restore'

    ## Video Capture

    - name: Restore dependencies $env:Solution_Name_VC1
      run: 'dotnet restore "$env:Solution_Name_VC1"'

    - name: Build app for release $env:Solution_Name_VC1
      run: 'dotnet build "$env:Solution_Name_VC1" --configuration Release --no-restore'
